/**
 */
package interrapidisimo.domain.provider;

import interrapidisimo.domain.util.DomainAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DomainItemProviderAdapterFactory extends DomainAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DomainItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Cliente} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClienteItemProvider clienteItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Cliente}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClienteAdapter() {
		if (clienteItemProvider == null) {
			clienteItemProvider = new ClienteItemProvider(this);
		}

		return clienteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Domain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainItemProvider domainItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Domain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainAdapter() {
		if (domainItemProvider == null) {
			domainItemProvider = new DomainItemProvider(this);
		}

		return domainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Empleado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmpleadoItemProvider empleadoItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Empleado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmpleadoAdapter() {
		if (empleadoItemProvider == null) {
			empleadoItemProvider = new EmpleadoItemProvider(this);
		}

		return empleadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.FactoryBodega} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FactoryBodegaItemProvider factoryBodegaItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.FactoryBodega}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFactoryBodegaAdapter() {
		if (factoryBodegaItemProvider == null) {
			factoryBodegaItemProvider = new FactoryBodegaItemProvider(this);
		}

		return factoryBodegaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.FactoryGestionHumana} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FactoryGestionHumanaItemProvider factoryGestionHumanaItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.FactoryGestionHumana}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFactoryGestionHumanaAdapter() {
		if (factoryGestionHumanaItemProvider == null) {
			factoryGestionHumanaItemProvider = new FactoryGestionHumanaItemProvider(this);
		}

		return factoryGestionHumanaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.FactoryPago} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FactoryPagoItemProvider factoryPagoItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.FactoryPago}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFactoryPagoAdapter() {
		if (factoryPagoItemProvider == null) {
			factoryPagoItemProvider = new FactoryPagoItemProvider(this);
		}

		return factoryPagoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Factura} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FacturaItemProvider facturaItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Factura}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFacturaAdapter() {
		if (facturaItemProvider == null) {
			facturaItemProvider = new FacturaItemProvider(this);
		}

		return facturaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Guia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuiaItemProvider guiaItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Guia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuiaAdapter() {
		if (guiaItemProvider == null) {
			guiaItemProvider = new GuiaItemProvider(this);
		}

		return guiaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Paquete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaqueteItemProvider paqueteItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Paquete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaqueteAdapter() {
		if (paqueteItemProvider == null) {
			paqueteItemProvider = new PaqueteItemProvider(this);
		}

		return paqueteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link interrapidisimo.domain.Transportador} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransportadorItemProvider transportadorItemProvider;

	/**
	 * This creates an adapter for a {@link interrapidisimo.domain.Transportador}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransportadorAdapter() {
		if (transportadorItemProvider == null) {
			transportadorItemProvider = new TransportadorItemProvider(this);
		}

		return transportadorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (clienteItemProvider != null) clienteItemProvider.dispose();
		if (domainItemProvider != null) domainItemProvider.dispose();
		if (empleadoItemProvider != null) empleadoItemProvider.dispose();
		if (factoryBodegaItemProvider != null) factoryBodegaItemProvider.dispose();
		if (factoryGestionHumanaItemProvider != null) factoryGestionHumanaItemProvider.dispose();
		if (factoryPagoItemProvider != null) factoryPagoItemProvider.dispose();
		if (facturaItemProvider != null) facturaItemProvider.dispose();
		if (guiaItemProvider != null) guiaItemProvider.dispose();
		if (paqueteItemProvider != null) paqueteItemProvider.dispose();
		if (transportadorItemProvider != null) transportadorItemProvider.dispose();
	}

}
